package:
   name: aesop
   version: 0.0.2

source:
   git_rev: latest
   git_url: https://github.com/rohithmohan/aesop-python.git

requirements:
   build:
      - python
      - scipy
      - numpy

   run:
      - python
      - scipy
      - numpy

test:
   imports:
      - prody
      - gridDataFormats
      - multiprocessing
      - scipy
      - numpy

about:
   home: https://github.com/rohithmohan/aesop-python
   license: MIT
   license_file: LICENSE
