package:
   name: aesop
   version: "0.0.2"

source:
   git_rev: "0.0.2"
   git_url: https://github.com/rohithmohan/aesop-python.git

requirements:
   build:
      - python
      - scipy
      - numpy
      - prody
      - griddataformats

   run:
      - python
      - scipy
      - numpy
      - prody
      - griddataformats

test:
   imports:
      - aesop
      - aesop.aesop

about:
   home: https://github.com/rohithmohan/aesop-python
   license: MIT
   license_file: LICENSE
